### ISSUE TITLE
Seems not working anymore

### ISSUE THREAD

**Issue by balalaXD** [michael-heerdegen/on-screen.el#2]
"GNU Emacs 25.3.1 (x86_64-w64-mingw32)
 of 2017-09-13"

**Comment by michael-heerdegen** [comment]
Hmm, it works well here.  I'm currently using Emacs master.  Hard to guess why it doesn't work for you without more info.  Maybe it depends on your settings.  Any idea how I can help?

**Comment by balalaXD** [comment]
NOOOO!!!!! FIXED!!! :smile: 
https://github.com/michael-heerdegen/on-screen.el/blob/206468aa4de299ad26c2db12b757f5ad7290912f/on-screen.el#L11
Download package `cl-lib-highlight` fix the problem.

**Comment by michael-heerdegen** [comment]
Ok, great.

Yes, I wanted  the fringe markers to be unobtrusive unless you directly look at the fringe.  But you can change the color by customizing the "on-screen-fringe" to a face that's better visible - warning or success for example.
